### ISSUE TITLE
Line Bordered Empty Button to Colored image transition 

### ISSUE THREAD

**Issue by ugur10** [631106979/WCLShineButton#10]
Hi,

How can we start with the left image, and end with the right image? Images can be different than this of course.

<img width="193" alt="screen shot 2017-05-09 at 09 16 59" src="https://cloud.githubusercontent.com/assets/20268759/25926247/dce83518-35f6-11e7-8ef9-4f6b2c139122.png">

**Comment by imwcl** [comment]
sorry,It is can't do that,it may be solved in later versions

**Comment by imwcl** [comment]
solved

**Comment by annjawn** [comment]
Do we have to use two different images in this case?
