### ISSUE TITLE
Can't use WCLShineButton in storyboard

### ISSUE THREAD

**Issue by ghysrc** [631106979/WCLShineButton#11]
Care to support storyboard?

**Comment by imwcl** [comment]
sorry,It is not support now,The next version could be supported

**Comment by imwcl** [comment]
supported

**Comment by ghysrc** [comment]
@imwcl Thanks. But it seemed the newest pods doesn't have the same code as your repository.

![164702](https://user-images.githubusercontent.com/4082752/31812834-e4b4acc2-b549-11e7-85e3-bd6f1a8312ec.png)
![164734](https://user-images.githubusercontent.com/4082752/31812839-ea659262-b549-11e7-9c0e-0786360932b0.png)
Doesn't see something like 'IBDesignable'...

**Comment by imwcl** [comment]
sorry,I seem to have made a mistake,but it's all right now,you can try it,1.0.7
