### ISSUE TITLE
Crash on 32 bit devices

### ISSUE THREAD

**Issue by ryandailey100** [631106979/WCLShineButton#9]
I noticed a crash when running on older devices. This crashes the app on an iPhone 5, but not 5s. Here is a screenshot to help understand where the app crashes. 

<img width="1183" alt="screen shot 2017-05-07 at 11 50 33 pm" src="https://cloud.githubusercontent.com/assets/15038444/25789634/06cc15f8-3380-11e7-93ff-53c49386e0e8.png">

**Comment by imwcl** [comment]
thx，has been solved
